import { compressTsx } from "./src/compress.js"
import { defaultConfig } from "./src/config.js"

const source = `// Generated by DRX. Do not edit directly.
// Source: src-drx/app/page.tsx.drx

"use client"

import { useActionState } from 'react';
`
console.log(compressTsx(source, defaultConfig, { file: "page.tsx" }))
