// Generated by DRX. Do not edit directly.
// Source: src-drx/app/page.drx

import { FileText, Search, Sparkles } from "lucide-react";

export default function Page() {
  return (
    <main className="min-h-screen bg-neutral-950 text-white">
      <Hero />
      <Features />
      <CTA />
    </main>
  );
}

function Hero() {
  return (
    <section className="mx-auto max-w-6xl px-6 py-24">
      <p className="mb-4 text-sm font-semibold text-blue-400">LicitadovAI</p>
      <h1 className="max-w-3xl text-5xl font-bold tracking-tight">
        Analiza licitaciones públicas con IA
      </h1>
      <p className="mt-6 max-w-2xl text-lg text-neutral-300">
        Resume documentos, encuentra requisitos y decide mejor antes de
        presentarte.
      </p>
      <Link
        className="mt-8 inline-flex rounded-xl bg-blue-500 px-6 py-3 font-semibold"
        href="/app"
      >
        Probar gratis
      </Link>
    </section>
  );
}

function Features() {
  return (
    <section className="mx-auto grid max-w-6xl gap-6 px-6 pb-24 md:grid-cols-3">
      <Feature
        icon={Search}
        title="Busca"
        text="Encuentra oportunidades relevantes."
      />
      <Feature
        icon={FileText}
        title="Resume"
        text="Convierte documentos largos en puntos claros."
      />
      <Feature
        icon={Sparkles}
        title="Decide"
        text="Evalúa si merece la pena presentarte."
      />
    </section>
  );
}

function Feature({ icon: Icon, title, text }) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
      <Icon className="size-7 text-blue-400" />
      <h2 className="mt-5 text-xl font-bold">{title}</h2>
      <p className="mt-2 text-neutral-400">{text}</p>
    </div>
  );
}

function CTA() {
  return (
    <section className="mx-auto max-w-6xl px-6 pb-24">
      <div className="rounded-3xl bg-white p-10 text-neutral-950">
        <h2 className="text-3xl font-bold">Empieza con una licitación real</h2>
        <p className="mt-3 text-neutral-600">
          Pega el enlace o documento y obtén un primer resumen.
        </p>
        <Link
          className="mt-6 inline-flex rounded-xl bg-neutral-950 px-6 py-3 font-semibold text-white"
          href="/app"
        >
          Abrir herramienta
        </Link>
      </div>
    </section>
  );
}
