// Generated by DRX. Do not edit directly.
// Source: src-drx/aiContext.drx

import fg from "fast-glob"
import fs from "fs-extra"
import path from "node:path"
import { DrxConfig } from "./config.js"

type ProjectSummary = {
  generatedAt: string
  sourceDir: string
  outDir: string
  drxFiles: string[]
  tsxFiles: string[]
  contentFiles: string[]
  configFiles: string[]
  routes: string[]
  components: string[]
  apiFiles: string[]
  symbols: ProjectSymbol[]
}
type ProjectSymbol = {
  name: string
  kind:
    | "default-function"
    | "function"
    | "exported-function"
    | "state"
    | "effect"
    | "import"
  file: string
  line: number
}

export async function generateAiContext(cwd: string, config: DrxConfig) {
  const drxRoot = path.join(cwd, config.sourceDir)

  const outRoot = path.join(cwd, config.outDir)

  const drxFiles = await listFiles(drxRoot, "**/*.drx", cwd)

  const tsxFiles = await listFiles(
    outRoot,
    ["**/*.{tsx,jsx}", "**/route.{ts,js}"],
    cwd,
    config.ignore,
  )

  const contentFiles = await listFiles(
    outRoot,
    ["**/*.{md,mdx}", "content/**/*"],
    cwd,
    config.ignore,
  )

  const configFiles = await listFiles(
    cwd,
    [
      "next.config.*",
      "vite.config.*",
      "theme.config.*",
      "tailwind.config.*",
      "postcss.config.*",
      "package.json",
    ],
    cwd,
    config.ignore,
  )

  const symbols = await collectDrxSymbols(cwd, drxFiles)

  const summary: ProjectSummary = {
    generatedAt: new Date().toISOString(),
    sourceDir: config.sourceDir,
    outDir: config.outDir,
    drxFiles,
    tsxFiles,
    contentFiles,
    configFiles,
    routes: findRoutes(drxFiles, tsxFiles, contentFiles),
    components: findComponents(drxFiles, tsxFiles),
    apiFiles: tsxFiles.filter(
      (file) =>
        /(^|\/)(api|route)\//.test(file) ||
        file.endsWith("/route.ts") ||
        file.endsWith("/route.tsx"),
    ),
    symbols,
  }

  const metaDir = path.join(cwd, ".drx")

  await fs.ensureDir(metaDir)
  await fs.writeFile(path.join(metaDir, "rules.md"), rulesMarkdown(config))
  await fs.writeJson(path.join(metaDir, "manifest.json"), summary, {
    spaces: 2,
  })
  await fs.writeFile(
    path.join(metaDir, "ai-context.md"),
    contextMarkdown(summary, config),
  )

  return summary
}

async function listFiles(
  root: string,
  pattern: string | string[],
  cwd: string,
  ignore: string[] = [],
) {
  if (!(await fs.pathExists(root))) return []

  return fg(pattern, { cwd: root, absolute: true, ignore }).then((files) =>
    files.map((file) => path.relative(cwd, file)).sort(),
  )
}

function findRoutes(
  drxFiles: string[],
  tsxFiles: string[],
  contentFiles: string[],
) {
  return [...drxFiles, ...tsxFiles, ...contentFiles]
    .filter(
      (file) =>
        /(^|\/)app\/.*(page|layout|route)\.(drx|tsx|ts|jsx|js)$/.test(file) ||
        /(^|\/)pages\/.+\.(drx|tsx|jsx|mdx|md)$/.test(file),
    )
    .sort()
}

function findComponents(drxFiles: string[], tsxFiles: string[]) {
  return [...drxFiles, ...tsxFiles]
    .filter((file) => /(^|\/)components\/.+\.(drx|tsx|ts|jsx|js)$/.test(file))
    .sort()
}

function contextMarkdown(summary: ProjectSummary, config: DrxConfig) {
  return `# DRX AI Context
  Generated: ${summary.generatedAt}
  ## Project
  - DRX source: \`${summary.sourceDir}\`
  - Generated/runtime source: \`${summary.outDir}\`
  - Framework: \`${config.framework}\`
  - Ignore patterns: ${config.ignore.map((item) => `\`${item}\``).join(", ")}
  ## How To Work
  1. Read \`.drx/rules.md\`.
  2. Prefer editing \`${summary.sourceDir}\` when the feature touches React/Next UI.
  3. Run \`pnpm dev -- check\`.
  4. Run \`pnpm dev -- expand\`.
  5. Do not edit generated TSX directly unless explicitly requested.
  ## Routes
  ${list(summary.routes)}
  ## Components
  ${list(summary.components)}
  ## Content Files
  ${list(summary.contentFiles)}
  ## Config Files
  ${list(summary.configFiles)}
  ## DRX Symbols
  ${symbolList(summary.symbols)}
  ## API / Backend Files
  ${list(summary.apiFiles)}
  ## Aliases
  ### Imports
  ${aliasList(config.aliases)}
  ### Tags
  ${aliasList(config.tagAliases)}
  ### Events
  ${aliasList(config.eventAliases)}
  `
}

function rulesMarkdown(config: DrxConfig) {
  return `# DRX Rules
  DRX is a compact JSX-compatible syntax that compiles to React/Next TSX.
  Core rules:
  - \`i X f pkg\` = \`import X from "pkg"\`
  - \`i {A,B} f pkg\` = \`import { A, B } from "pkg"\`
  - \`ed fn Name()\` = \`export default function Name()\`
  - \`ex fn Name()\` = \`export function Name()\`
  - \`fn Name()\` = \`function Name()\`
  - \`c name = value\` = \`const name = value\`
  - \`l name = value\` = \`let name = value\`
  - \`aw\` = \`await\`
  - \`r value\` = \`return value\`
  - \`st name = value\` = \`const [name, setName] = useState(value)\`
  - \`ef [deps]\` = \`useEffect(() => {}, [deps])\`
  - \`ui\` starts the returned JSX block
  - \`.class\` inside a tag becomes \`className\`
  - \`raw\` preserves full JS/TS/TSX
  Prefer readable names. Use \`raw\` for unsupported syntax.
  Known tag aliases:
  ${aliasList(config.tagAliases)}
  `
}

function list(items: string[]) {
  return items.length
    ? items.map((item) => `- \`${item}\``).join("\n")
    : "- None found"
}

async function collectDrxSymbols(cwd: string, files: string[]) {
  const symbols = []

  for (const file of files) {
    const source = await fs.readFile(path.join(cwd, file), "utf8")
    source.split(/\r?\n/).forEach((line, index) => {
      const trimmed = line.trim()
      const fn = trimmed.match(
        /^(ed|ex)?\s*(async\s+)?fn\s+([A-Za-z_$][\w$]*)\(/,
      )
      if (fn) {
        symbols.push({
          name: fn[3],
          kind:
            fn[1] === "ed"
              ? "default-function"
              : fn[1] === "ex"
                ? "exported-function"
                : "function",
          file,
          line: index + 1,
        })
        return
      }
      const state = trimmed.match(/^st\s+([A-Za-z_$][\w$]*)\s*=/)
      if (state) {
        symbols.push({ name: state[1], kind: "state", file, line: index + 1 })
        return
      }
      if (/^ef\s+\[/.test(trimmed)) {
        symbols.push({
          name: "useEffect",
          kind: "effect",
          file,
          line: index + 1,
        })
        return
      }
      const imported = trimmed.match(/^i\s+(.+)\s+f\s+(.+)$/)
      if (imported)
        symbols.push({
          name: imported[1],
          kind: "import",
          file,
          line: index + 1,
        })
    })
  }

  return symbols
}

function symbolList(symbols: ProjectSymbol[]) {
  if (!symbols.length) return "- None found"

  return symbols
    .map(
      (symbol) =>
        `- \`${symbol.name}\` (${symbol.kind}) in \`${symbol.file}:${symbol.line}\``,
    )
    .join("\n")
}

function aliasList(record: Record<string, string>) {
  return Object.entries(record)
    .map(([key, value]) => `- \`${key}\` -> \`${value}\``)
    .join("\n")
}
