import ts from "typescript"
import { DrxConfig } from "./config.js"

type CompressOptions = {
  file?: string
}

const htmlTagAliases: Record<string, string> = {
  main: "m",
  section: "s",
  div: "d",
  span: "sp",
  button: "btn",
  header: "hdr",
  footer: "ftr",
  article: "art",
  form: "frm",
  label: "lbl",
  input: "inp",
  textarea: "ta",
  select: "sel",
  option: "opt"
}

const printer = ts.createPrinter({ removeComments: true })

export function compressTsx(source: string, config: DrxConfig, options: CompressOptions = {}) {
  const isTs = options.file?.endsWith(".ts") && !options.file?.endsWith(".d.ts")
  const scriptKind = isTs ? ts.ScriptKind.TS : ts.ScriptKind.TSX
  const sourceFile = ts.createSourceFile(options.file ?? "input.tsx", source, ts.ScriptTarget.Latest, true, scriptKind)
  const lines: string[] = []

  let currentRawGroup: ts.Node[] = []

  function flushRawGroup() {
    if (!currentRawGroup.length) return
    const nodes = ts.factory.createNodeArray(currentRawGroup)
    const code = printer.printList(ts.ListFormat.MultiLine, nodes, sourceFile)
    const formatted = code.replace(/^( {4})+/gm, (match) => "  ".repeat(match.length / 4)).replace(/\t/g, "  ")
    lines.push("raw", ...indentLines(formatted.split("\n"), 1))
    currentRawGroup = []
  }

  for (const statement of sourceFile.statements) {
    if (isGeneratedComment(statement, sourceFile)) continue
    const directive = getDirective(statement)
    if (directive) {
      flushRawGroup()
      lines.push(directive)
      continue
    }
    if (ts.isImportDeclaration(statement)) {
      const importLines = compressImport(statement, config, sourceFile)
      if (importLines[0] === "raw") {
        currentRawGroup.push(statement)
      } else {
        flushRawGroup()
        lines.push(...importLines)
      }
      continue
    }
    if (ts.isFunctionDeclaration(statement)) {
      if (!statement.name) {
        currentRawGroup.push(statement)
        continue
      }
      flushRawGroup()
      lines.push(...compressFunction(statement, sourceFile))
      continue
    }
    if (ts.isVariableStatement(statement)) {
      const component = compressArrowComponent(statement, sourceFile)
      if (component) {
        flushRawGroup()
        lines.push(...component)
        continue
      }
    }
    currentRawGroup.push(statement)
  }
  flushRawGroup()

  return compactBlankLines(lines).join("\n") + "\n"
}

function getDirective(statement: ts.Statement) {
  if (!ts.isExpressionStatement(statement)) return null
  if (!ts.isStringLiteral(statement.expression)) return null
  return JSON.stringify(statement.expression.text)
}

function isGeneratedComment(statement: ts.Statement, sourceFile: ts.SourceFile) {
  const comments = ts.getLeadingCommentRanges(sourceFile.getFullText(), statement.getFullStart()) ?? []
  return comments.some((comment) => sourceFile.getFullText().slice(comment.pos, comment.end).includes("Generated by DRX"))
}

function compressImport(statement: ts.ImportDeclaration, config: DrxConfig, sourceFile: ts.SourceFile) {
  const source = statement.moduleSpecifier.getText().replace(/^["']|["']$/g, "")
  const sourceAlias = reverseLookup(config.aliases, source) ?? JSON.stringify(source)
  const clause = statement.importClause
  if (!clause) return rawBlock(statement, sourceFile, 0)
  if (clause.isTypeOnly) return rawBlock(statement, sourceFile, 0)

  const lines: string[] = []
  if (clause.name) lines.push(`i ${clause.name.text} f ${sourceAlias}`)

  if (clause.namedBindings && ts.isNamedImports(clause.namedBindings)) {
    if (clause.namedBindings.elements.some((element) => element.isTypeOnly)) return rawBlock(statement, sourceFile, 0)
    const names = clause.namedBindings.elements.map((element) => reverseLookup(config.namedAliases, element.name.text) ?? element.name.text)
    lines.push(`i {${names.join(",")}} f ${sourceAlias}`)
    return lines
  }

  if (lines.length) return lines
  return rawBlock(statement, sourceFile, 0)
}

function compressFunction(fn: ts.FunctionDeclaration, sourceFile: ts.SourceFile) {
  if (!fn.name) return rawBlock(fn, sourceFile, 0)

  const exportDefault = hasModifier(fn, ts.SyntaxKind.DefaultKeyword) && hasModifier(fn, ts.SyntaxKind.ExportKeyword)
  const exportNamed = !exportDefault && hasModifier(fn, ts.SyntaxKind.ExportKeyword)
  const asyncFn = hasModifier(fn, ts.SyntaxKind.AsyncKeyword)
  const params = fn.parameters.map((param) => printer.printNode(ts.EmitHint.Unspecified, param, sourceFile).replace(/\s+/g, " ").trim()).join(", ")
  const exportPrefix = exportDefault ? "ed " : exportNamed ? "ex " : ""
  const header = `${exportPrefix}${asyncFn ? "async " : ""}fn ${fn.name.text}(${params})`
  const lines = [header]

  if (!fn.body) return lines
  const bodyLines = compressFunctionBody(fn.body, sourceFile)
  lines.push(...indentLines(bodyLines, 1))
  return lines
}

function compressArrowComponent(statement: ts.VariableStatement, sourceFile: ts.SourceFile) {
  if (statement.declarationList.declarations.length !== 1) return null
  const declaration = statement.declarationList.declarations[0]
  if (!ts.isIdentifier(declaration.name) || !declaration.initializer) return null
  const initializer = declaration.initializer
  if (!ts.isArrowFunction(initializer) && !ts.isFunctionExpression(initializer)) return null
  if (!returnsJsx(initializer.body)) return null

  const exportNamed = hasModifier(statement, ts.SyntaxKind.ExportKeyword)
  const asyncFn = hasModifier(initializer, ts.SyntaxKind.AsyncKeyword)
  const params = initializer.parameters.map((param) => printer.printNode(ts.EmitHint.Unspecified, param, sourceFile).replace(/\s+/g, " ").trim()).join(", ")
  const header = `${exportNamed ? "ex " : ""}${asyncFn ? "async " : ""}fn ${declaration.name.text}(${params})`
  const lines = [header]

  if (ts.isBlock(initializer.body)) {
    lines.push(...indentLines(compressFunctionBody(initializer.body, sourceFile), 1))
  } else if (isJsx(initializer.body)) {
    lines.push("  ui")
    lines.push(...indentLines(compressJsxNode(initializer.body, sourceFile), 2))
  }

  return lines
}

function compressFunctionBody(body: ts.Block, sourceFile: ts.SourceFile) {
  const lines: string[] = []

  let currentRawGroup: ts.Node[] = []

  function flushRawGroup() {
    if (!currentRawGroup.length) return
    const nodes = ts.factory.createNodeArray(currentRawGroup)
    const code = printer.printList(ts.ListFormat.MultiLine, nodes, sourceFile)
    const formatted = code.replace(/^( {4})+/gm, (match) => "  ".repeat(match.length / 4)).replace(/\t/g, "  ")
    lines.push("raw", ...indentLines(formatted.split("\n"), 1))
    currentRawGroup = []
  }

  for (const statement of body.statements) {
    if (ts.isReturnStatement(statement) && statement.expression && isJsx(statement.expression)) {
      flushRawGroup()
      lines.push("ui")
      lines.push(...indentLines(compressJsxNode(statement.expression, sourceFile), 1))
      continue
    }

    const state = compressUseState(statement, sourceFile)
    if (state) {
      flushRawGroup()
      lines.push(state)
      continue
    }

    const effect = compressUseEffect(statement, sourceFile)
    if (effect) {
      flushRawGroup()
      lines.push(...effect)
      continue
    }

    const simple = compressSimpleStatement(statement, sourceFile)
    if (simple) {
      flushRawGroup()
      lines.push(simple)
      continue
    }

    currentRawGroup.push(statement)
  }
  flushRawGroup()

  return lines
}

function compressUseState(statement: ts.Statement, sourceFile: ts.SourceFile) {
  if (!ts.isVariableStatement(statement)) return null
  if (statement.declarationList.declarations.length !== 1) return null
  const declaration = statement.declarationList.declarations[0]
  if (!ts.isArrayBindingPattern(declaration.name) || declaration.name.elements.length < 1) return null
  if (!declaration.initializer || !ts.isCallExpression(declaration.initializer)) return null
  if (declaration.initializer.expression.getText(sourceFile) !== "useState") return null
  const firstElement = declaration.name.elements[0]
  if (ts.isOmittedExpression(firstElement)) return null
  if (!ts.isIdentifier(firstElement.name)) return null
  const stateName = firstElement.name.text
  let initial = "undefined"
  if (declaration.initializer.arguments[0]) {
    const code = printer.printNode(ts.EmitHint.Unspecified, declaration.initializer.arguments[0], sourceFile)
    initial = code.replace(/\s+/g, " ").trim()
  }
  return `st ${stateName} = ${initial}`
}

function compressUseEffect(statement: ts.Statement, sourceFile: ts.SourceFile) {
  if (!ts.isExpressionStatement(statement)) return null
  const expr = statement.expression
  if (!ts.isCallExpression(expr) || expr.expression.getText(sourceFile) !== "useEffect") return null
  const callback = expr.arguments[0]
  let deps = expr.arguments[1] ? printer.printNode(ts.EmitHint.Unspecified, expr.arguments[1], sourceFile) : "[]"
  deps = deps.replace(/\s+/g, " ").trim()
  if (!callback || (!ts.isArrowFunction(callback) && !ts.isFunctionExpression(callback))) return null
  if (!ts.isBlock(callback.body)) return null

  const lines = [`ef ${deps}`]
  for (const inner of callback.body.statements) {
    lines.push(...indentLines([inner.getText(sourceFile)], 1))
  }
  return lines
}

function compressSimpleStatement(statement: ts.Statement, sourceFile: ts.SourceFile) {
  if (ts.isVariableStatement(statement) && statement.declarationList.declarations.length === 1) {
    const declaration = statement.declarationList.declarations[0]
    const kind = (statement.declarationList.flags & ts.NodeFlags.Let) !== 0 ? "l" : "c"
    if (declaration.initializer) {
      const name = printer.printNode(ts.EmitHint.Unspecified, declaration.name, sourceFile).replace(/\s+/g, " ").trim()
      const initializer = printer.printNode(ts.EmitHint.Unspecified, declaration.initializer, sourceFile).replace(/\s+/g, " ").trim()
      return `${kind} ${name} = ${initializer.replace(/\bawait\b/g, "aw")}`
    }
  }
  if (ts.isReturnStatement(statement) && statement.expression) {
    const expression = printer.printNode(ts.EmitHint.Unspecified, statement.expression, sourceFile).replace(/\s+/g, " ").trim()
    return `r ${expression.replace(/\bawait\b/g, "aw")}`
  }
  return null
}

function compressJsxNode(node: ts.Node, sourceFile: ts.SourceFile): string[] {
  if (ts.isParenthesizedExpression(node)) return compressJsxNode(node.expression, sourceFile)
  if (ts.isJsxElement(node)) {
    const tag = compressTag(node.openingElement.tagName.getText(sourceFile))
    const attrs = compressAttributes(node.openingElement.attributes, sourceFile)
    const open = `<${tag}${attrs ? ` ${attrs}` : ""}>`
    const close = `</${tag}>`
    const childLines = compressJsxChildren(node.children, sourceFile)
    if (childLines.length === 1 && isInlineJsxChild(childLines[0])) return [`${open}${childLines[0]}${close}`]
    return [open, ...indentLines(childLines, 1), close]
  }
  if (ts.isJsxSelfClosingElement(node)) {
    const tag = compressTag(node.tagName.getText(sourceFile))
    const attrs = compressAttributes(node.attributes, sourceFile)
    return [`<${tag}${attrs ? ` ${attrs}` : ""} />`]
  }
  if (ts.isJsxFragment(node)) {
    return ["<>", ...indentLines(compressJsxChildren(node.children, sourceFile), 1), "</>"]
  }
  if (ts.isJsxExpression(node)) {
    if (!node.expression) return []
    const code = printer.printNode(ts.EmitHint.Unspecified, node.expression, sourceFile)
    const singleLine = code.replace(/\r?\n\s*/g, " ")
    return [`{${singleLine}}`]
  }
  if (ts.isJsxText(node)) {
    const text = node.getText(sourceFile).replace(/\s+/g, " ").trim()
    return text ? [text] : []
  }
  const code = printer.printNode(ts.EmitHint.Unspecified, node, sourceFile)
  const singleLine = code.replace(/\r?\n\s*/g, " ")
  return [`{${singleLine}}`]
}

function compressJsxChildren(children: ts.NodeArray<ts.JsxChild>, sourceFile: ts.SourceFile) {
  return children.flatMap((child) => compressJsxNode(child, sourceFile)).filter(Boolean)
}

function compressAttributes(attributes: ts.JsxAttributes, sourceFile: ts.SourceFile) {
  const parts: string[] = []
  for (const prop of attributes.properties) {
    if (!ts.isJsxAttribute(prop)) {
      const code = printer.printNode(ts.EmitHint.Unspecified, prop, sourceFile)
      const singleLine = code.replace(/\r?\n\s*/g, " ")
      parts.push(singleLine)
      continue
    }
    const name = prop.name.getText(sourceFile)
    const value = prop.initializer
    if (name === "className" && value && ts.isStringLiteral(value)) {
      const classes = value.text.split(/\s+/).filter(Boolean)
      const safeClasses = classes.every(c => /^[a-zA-Z0-9_\-:]+$/.test(c))
      if (safeClasses) {
        parts.push(...classes.map((klass) => `.${klass}`))
        continue
      }
    }
    const eventAlias = reverseEventAlias(name)
    const propName = eventAlias ?? name
    if (!value) {
      parts.push(propName)
      continue
    }
    if (ts.isStringLiteral(value)) {
      parts.push(`${propName}=${JSON.stringify(value.text)}`)
      continue
    }
    if (ts.isJsxExpression(value) && value.expression) {
      const code = printer.printNode(ts.EmitHint.Unspecified, value.expression, sourceFile)
      const singleLine = code.replace(/\r?\n\s*/g, " ")
      parts.push(`${propName}=${formatCompressedExpression(singleLine)}`)
      continue
    }
    parts.push(`${propName}=${value.getText(sourceFile)}`)
  }
  return parts.join(" ")
}

function formatCompressedExpression(value: string) {
  if (/^[A-Za-z_$][\w$]*(?:\.[A-Za-z_$][\w$]*)*$/.test(value)) return value
  if (/^(true|false|null|undefined|\d+(?:\.\d+)?)$/.test(value)) return value
  return `{${value}}`
}

function compressTag(tag: string) {
  if (/^[A-Z]/.test(tag)) return tag
  return htmlTagAliases[tag] ?? tag
}

function reverseEventAlias(eventName: string) {
  const entries: Array<[string, string]> = [
    ["@click", "onClick"],
    ["@change", "onChange"],
    ["@submit", "onSubmit"],
    ["@input", "onInput"],
    ["@focus", "onFocus"],
    ["@blur", "onBlur"],
    ["@key", "onKeyDown"]
  ]
  return entries.find(([, value]) => value === eventName)?.[0] ?? null
}

function hasModifier(node: ts.Node, kind: ts.SyntaxKind) {
  return Boolean(ts.canHaveModifiers(node) && ts.getModifiers(node)?.some((modifier) => modifier.kind === kind))
}

function isJsx(node: ts.Node): boolean {
  if (ts.isJsxElement(node) || ts.isJsxSelfClosingElement(node) || ts.isJsxFragment(node)) return true
  if (ts.isParenthesizedExpression(node)) return isJsx(node.expression)
  return false
}

function returnsJsx(node: ts.Node): boolean {
  if (isJsx(node)) return true
  if (!ts.isBlock(node)) return false
  return node.statements.some((statement) => ts.isReturnStatement(statement) && Boolean(statement.expression && isJsx(statement.expression)))
}

function isInlineJsxChild(line: string) {
  return !line.startsWith("<") || line.endsWith("/>") || line.includes("</")
}

function rawBlock(node: ts.Node, sourceFile: ts.SourceFile, level: number) {
  const code = printer.printNode(ts.EmitHint.Unspecified, node, sourceFile)
  const formatted = code.replace(/^( {4})+/gm, (match) => "  ".repeat(match.length / 4)).replace(/\t/g, "  ")
  return ["raw", ...indentLines(formatted.split("\n"), level + 1)]
}

function indentLines(lines: string[], level: number) {
  const prefix = "  ".repeat(level)
  return lines.map((line) => (line ? `${prefix}${line}` : line))
}

function reverseLookup(record: Record<string, string>, value: string) {
  return Object.entries(record).find(([, entryValue]) => entryValue === value)?.[0] ?? null
}

function compactBlankLines(lines: string[]) {
  const output: string[] = []
  for (const line of lines) {
    if (!line && output.at(-1) === "") continue
    output.push(line)
    if (/^(?:"[^"]+"|i |raw|ed |async |fn )/.test(line)) output.push("")
  }
  while (output.at(-1) === "") output.pop()
  return output
}
