import prettier from "prettier"
import { Node, Program } from "./ast.js"
import { DrxConfig } from "./config.js"
import { normalizeParams } from "./strings.js"

export async function compileDrx(source: string, config: DrxConfig, options: { file?: string; sourcePath?: string } = {}) {
  const { parseDrx } = await import("./parser.js")
  const program = parseDrx(source, config, options.file)
  let tsx = generateProgram(program, config, options.sourcePath)
  if (config.formatWithPrettier) {
    tsx = await prettier.format(tsx, { parser: "typescript", semi: false })
  }
  return tsx
}

export function generateProgram(program: Program, config: DrxConfig, sourcePath?: string) {
  const imports = generateImports(program, config)
  const chunks: string[] = []
  const directives = program.nodes.filter((node) => node.type === "directive")
  const rest = program.nodes.filter((node) => node.type !== "directive" && node.type !== "import")

  if (config.generatedHeader && sourcePath) {
    chunks.push(`// Generated by DRX. Do not edit directly.\n// Source: ${sourcePath}`)
  }
  chunks.push(...directives.map((node) => node.value))
  if (imports.length) chunks.push(imports.join("\n"))
  chunks.push(...rest.map((node) => generateNode(node)))
  return chunks.filter(Boolean).join("\n\n")
}

function generateImports(program: Program, config: DrxConfig) {
  const importsBySource = new Map<string, { defaults: string[]; named: Set<string> }>()

  for (const node of program.nodes) {
    if (node.type !== "import") continue
    const source = config.aliases[node.source] ?? stripQuotes(node.source)
    const target = importsBySource.get(source) ?? { defaults: [], named: new Set<string>() }
    if (node.imported.startsWith("{") && node.imported.endsWith("}")) {
      for (const item of node.imported.slice(1, -1).split(",").map((part) => part.trim()).filter(Boolean)) {
        target.named.add(config.namedAliases[item] ?? item)
      }
    } else {
      target.defaults.push(node.imported)
    }
    importsBySource.set(source, target)
  }

  if (config.autoImportHooks && (program.usesState || program.usesEffect)) {
    const react = importsBySource.get("react") ?? { defaults: [], named: new Set<string>() }
    if (program.usesState) react.named.add("useState")
    if (program.usesEffect) react.named.add("useEffect")
    importsBySource.set("react", react)
  }

  const result: string[] = []
  for (const [source, value] of importsBySource.entries()) {
    const named = Array.from(value.named).sort()
    if (value.defaults.length > 0) {
      let namedProcessed = false
      for (const def of value.defaults) {
        const parts = [def]
        if (named.length > 0 && def === value.defaults[0]) {
          parts.push(`{ ${named.join(", ")} }`)
          namedProcessed = true
        }
        result.push(`import ${parts.join(", ")} from "${source}"`)
      }
      if (named.length > 0 && !namedProcessed) {
        result.push(`import { ${named.join(", ")} } from "${source}"`)
      }
    } else if (named.length > 0) {
      result.push(`import { ${named.join(", ")} } from "${source}"`)
    }
  }
  return result
}

function generateNode(node: Node): string {
  if (node.type === "raw") return node.code
  if (node.type === "comment") return node.code
  if (node.type === "statement") return node.code
  if (node.type === "function") {
    const exportPrefix = node.exportDefault ? "export default " : node.exportNamed ? "export " : ""
    const typeParams = node.typeParams || ""
    const head = `${exportPrefix}${node.async ? "async " : ""}function ${node.name}${typeParams}(${normalizeParams(node.params)})`
    if (node.body.length === 0) {
      return `${head}`
    }
    const body = node.body.map((child) => {
      if (child.type === "ui") return `return (\n${indent(child.jsx)}\n)`
      if (child.type === "raw") return child.code
      if (child.type === "comment") return child.code
      if (child.type === "effect") return `useEffect(() => {\n${indent(child.code)}\n}, ${child.deps})`
      return child.code
    })
    return `${head} {\n${indent(body.join("\n\n"))}\n}`
  }
  return ""
}

function indent(value: string) {
  return value
    .split("\n")
    .map((line) => (line ? `  ${line}` : line))
    .join("\n")
}

function stripQuotes(value: string) {
  return value.replace(/^["']|["']$/g, "")
}
