// Generated by DRX. Do not edit directly.
// Source: src-drx/jsx.drx

import { DrxConfig } from "./config.js";
import { DrxError } from "./errors.js";
import { splitTopLevel } from "./strings.js";

type TagMatch = {
  full: string;
  closing: boolean;
  tag: string;
  attrs: string;
  selfClosing: boolean;
};

export function transformJsxLite(
  lines: string[],
  config: DrxConfig,
  file?: string,
) {
  const output = [];

  const stack = [];

  for (const item of lines) {
    const lineNo = Number(item.slice(0, item.indexOf(":")));
    const source = item.slice(item.indexOf(":") + 1);
    const transformed = transformLine(source, config, file, lineNo, stack);
    output.push(transformed);
  }
  if (stack.length) {
    const open = stack.at(-1)!;
    throw new DrxError({
      code: "DRX_UNCLOSED_TAG",
      message: `Unclosed JSX tag <${open.tag}>.`,
      file,
      line: open.line,
    });
  }

  return output.join("\n");
}

function transformLine(
  line: string,
  config: DrxConfig,
  file: string | undefined,
  lineNo: number,
  stack: { tag: string; line: number }[],
) {
  if (/^\s*if\s+/.test(line))
    return line.replace(/^(\s*)if\s+(.+)$/, "$1{$2 && (");
  if (/^\s*for\s+/.test(line)) {
    return line.replace(
      /^(\s*)for\s+(.+)\s+as\s+([A-Za-z_$][\w$]*)(?:\s*,\s*([A-Za-z_$][\w$]*))?\s*$/,
      (_, indent, list, item, index) => {
        const args = index ? `${item}, ${index}` : item;
        return `${indent}{${list}.map((${args}) => (`;
      },
    );
  }

  const matches = scanTags(line);

  let result = "";

  let cursor = 0;

  for (const match of matches) {
    const transformed = transformTag(match, config, file, lineNo, stack);
    const start = line.indexOf(match.full, cursor);
    result += line.slice(cursor, start) + transformed;
    cursor = start + match.full.length;
  }
  result += line.slice(cursor);
  result = unquoteTextOutsideTags(result);

  return result;
}

function scanTags(line: string) {
  const matches = [];

  let i = 0;

  while (i < line.length) {
    if (line[i] !== "<" || !/[A-Za-z/]/.test(line[i + 1] ?? "")) {
      i++;
      continue;
    }
    const start = i;
    let quote: string | null = null;
    let braceDepth = 0;
    i++;
    while (i < line.length) {
      const char = line[i];
      if (quote) {
        if (char === quote) quote = null;
        i++;
        continue;
      }
      if (char === '"' || char === "'") {
        quote = char;
        i++;
        continue;
      }
      if (char === "{") braceDepth++;
      if (char === "}") braceDepth--;
      if (char === ">" && braceDepth === 0) break;
      i++;
    }
    if (line[i] !== ">") break;
    const full = line.slice(start, i + 1);
    const parsed = full.match(/^<\/?\s*([A-Za-z][\w.]*)\b([\s\S]*?)\/?\s*>$/);
    if (parsed) {
      matches.push({
        full,
        closing: full.startsWith("</"),
        tag: parsed[1],
        attrs: parsed[2] ?? "",
        selfClosing: /\/\s*>$/.test(full),
      });
    }
    i++;
  }

  return matches;
}

function unquoteTextOutsideTags(line: string) {
  let result = "";

  let inTag = false;

  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (char === "<") inTag = true;
    if (char === ">") {
      inTag = false;
      result += char;
      continue;
    }
    if (!inTag && char === '"') continue;
    result += char;
  }

  return result;
}

function transformTag(
  match: TagMatch,
  config: DrxConfig,
  file: string | undefined,
  line: number,
  stack: { tag: string; line: number }[],
) {
  const tag = resolveTag(match.tag, config);

  if (match.closing) {
    const open = stack.pop();
    if (!open || open.tag !== tag) {
      throw new DrxError({
        code: "DRX_MISMATCHED_TAG",
        message: `Unexpected closing tag </${tag}>.`,
        file,
        line,
      });
    }
    return `</${tag}>`;
  }
  if (!match.selfClosing) stack.push({ tag, line });

  const attrs = transformAttrs(
    match.attrs.replace(/\/\s*$/, "").trim(),
    config,
    file,
    line,
  );

  const close = match.selfClosing ? " />" : ">";

  return `<${tag}${attrs ? ` ${attrs}` : ""}${close}`;
}

function resolveTag(tag: string, config: DrxConfig) {
  if (/^[A-Z]/.test(tag)) return config.componentAliases[tag] ?? tag;

  return config.tagAliases[tag] ?? tag;
}

function transformAttrs(
  source: string,
  config: DrxConfig,
  file: string | undefined,
  line: number,
) {
  if (!source) return "";

  const tokens = splitTopLevel(source);

  const classes = [];

  const attrs = [];

  let classNameIndex = -1;

  for (const token of tokens) {
    if (token.startsWith(".")) {
      classes.push(token.slice(1));
      continue;
    }
    if (token.startsWith("@")) {
      const [alias, rawValue] = splitAttr(token);
      const eventName = config.eventAliases[alias];
      if (!eventName) {
        throw new DrxError({
          code: "DRX_UNKNOWN_EVENT",
          message: `Unknown event alias "${alias}".`,
          file,
          line,
          hint: alias === "@clik" ? 'Did you mean "@click"?' : undefined,
        });
      }
      attrs.push(`${eventName}={${stripBraces(rawValue ?? "")}}`);
      continue;
    }
    const [name, rawValue] = splitAttr(token);
    if (rawValue === undefined) {
      attrs.push(name);
      continue;
    }
    const value = formatPropValue(rawValue);
    if (name === "className") classNameIndex = attrs.length;
    attrs.push(`${name}=${value}`);
  }
  if (classes.length) {
    if (classNameIndex >= 0) {
      attrs[classNameIndex] = attrs[classNameIndex].replace(
        /className="([^"]*)"/,
        (_, value) => `className="${value} ${classes.join(" ")}"`,
      );
    } else {
      attrs.unshift(`className="${classes.join(" ")}"`);
    }
  }

  return attrs.join(" ");
}

function splitAttr(token: string) {
  const index = token.indexOf("=");

  if (index === -1) return [token];

  return [token.slice(0, index), token.slice(index + 1)];
}

function stripBraces(value: string) {
  if (value.startsWith("{") && value.endsWith("}")) return value.slice(1, -1);

  return value;
}

function formatPropValue(value: string) {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  )
    return value;
  if (value.startsWith("{") && value.endsWith("}")) return value;

  return `{${value}}`;
}
