// Generated by DRX. Do not edit directly.
// Source: src-drx/parser.drx

import { FunctionBodyNode, Node, Program } from "./ast.js";
import { DrxConfig } from "./config.js";
import { DrxError } from "./errors.js";
import { transformJsxLite } from "./jsx.js";
import { replaceAw, setterName } from "./strings.js";

type Line = {
  no: number;
  indent: number;
  text: string;
};

export function parseDrx(source: string, config: DrxConfig, file?: string) {
  const lines = toLines(source, file);

  const nodes = [];

  let usesState = false;

  let usesEffect = false;

  let index = 0;

  while (index < lines.length) {
    const line = lines[index];
    if (line.indent !== 0) {
      throw new DrxError({
        code: "DRX_INVALID_INDENT",
        message: "Top-level lines must not be indented.",
        file,
        line: line.no,
      });
    }
    const parsed = parseTopLevel(lines, index, config, file);
    index = parsed.next;
    if (parsed.usesState) usesState = true;
    if (parsed.usesEffect) usesEffect = true;
    nodes.push(parsed.node);
  }

  return { nodes, usesState, usesEffect };
}

function toLines(source: string, file?: string) {
  return source
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((raw, i) => {
      if (raw.includes("\t")) {
        throw new DrxError({
          code: "DRX_TAB_INDENT",
          message: "Tabs are not allowed. Use 2 spaces per indent level.",
          file,
          line: i + 1,
        });
      }
      const spaces = raw.match(/^ */)?.[0].length ?? 0;
      if (spaces % 2 !== 0) {
        throw new DrxError({
          code: "DRX_INVALID_INDENT",
          message: "Indentation must use multiples of 2 spaces.",
          file,
          line: i + 1,
        });
      }
      return { no: i + 1, indent: spaces / 2, text: raw.trim() };
    })
    .filter((line) => line.text.length > 0);
}

function parseTopLevel(
  lines: Line[],
  index: number,
  config: DrxConfig,
  file?: string,
) {
  const line = lines[index];

  if (/^"[^"]+"$/.test(line.text)) {
    return {
      node: { type: "directive", value: line.text } as Node,
      next: index + 1,
    };
  }
  if (line.text.startsWith("//")) {
    return {
      node: { type: "comment", code: line.text, line: line.no } as Node,
      next: index + 1,
    };
  }
  if (line.text.startsWith("i ")) {
    const match = line.text.match(/^i\s+(.+)\s+f\s+(.+)$/);
    if (!match) {
      throw new DrxError({
        code: "DRX_INVALID_IMPORT",
        message:
          "Invalid import. Expected: i Name f source or i {A,B} f source.",
        file,
        line: line.no,
      });
    }
    return {
      node: {
        type: "import",
        imported: match[1].trim(),
        source: match[2].trim(),
        line: line.no,
      } as Node,
      next: index + 1,
    };
  }
  if (line.text === "raw") {
    const block = collectBlock(lines, index, 1);
    return {
      node: { type: "raw", code: block.text, line: line.no } as Node,
      next: block.next,
    };
  }

  const fn = parseFunctionHeader(line.text);

  if (fn) {
    const block = collectFunctionBody(lines, index, config, file);
    return {
      node: {
        type: "function",
        ...fn,
        body: block.body,
        line: line.no,
      } as Node,
      next: block.next,
      usesState: block.usesState,
      usesEffect: block.usesEffect,
    };
  }
  if (config.keepUnknownAsRaw) {
    return {
      node: { type: "raw", code: line.text, line: line.no } as Node,
      next: index + 1,
    };
  }
  throw new DrxError({
    code: "DRX_UNKNOWN_LINE",
    message: `Unknown DRX line: ${line.text}`,
    file,
    line: line.no,
  });
}

function parseFunctionHeader(text: string) {
  const match = text.match(
    /^(?:(ed|ex)\s+)?(async\s+)?fn\s+([A-Za-z_$][\w$]*)\((.*)\)$/,
  );

  if (!match) return null;
  return {
    exportDefault: match[1] === "ed",
    exportNamed: match[1] === "ex",
    async: Boolean(match[2]),
    name: match[3],
    params: match[4],
  };
}

function collectFunctionBody(
  lines: Line[],
  start: number,
  config: DrxConfig,
  file?: string,
) {
  const body = [];

  let usesState = false;

  let usesEffect = false;

  let index = start + 1;

  while (index < lines.length && lines[index].indent > lines[start].indent) {
    const line = lines[index];
    if (line.indent !== 1) {
      throw new DrxError({
        code: "DRX_INVALID_INDENT",
        message: "Function body lines must be indented one level.",
        file,
        line: line.no,
      });
    }
    if (line.text.startsWith("//")) {
      body.push({ type: "comment", code: line.text, line: line.no });
      index++;
      continue;
    }
    if (line.text === "ui") {
      const block = collectBlock(lines, index, 2);
      if (!block.text.trim()) {
        throw new DrxError({
          code: "DRX_EMPTY_UI",
          message: "ui block cannot be empty.",
          file,
          line: line.no,
        });
      }
      body.push({
        type: "ui",
        jsx: transformJsxLite(block.numberedLines, config, file),
        line: line.no,
      });
      index = block.next;
      continue;
    }
    if (line.text === "raw") {
      const block = collectBlock(lines, index, 2);
      body.push({ type: "raw", code: block.text, line: line.no });
      index = block.next;
      continue;
    }
    if (line.text.startsWith("st ")) {
      const match = line.text.match(/^st\s+([A-Za-z_$][\w$]*)\s*=\s*(.+)$/);
      if (!match)
        throw new DrxError({
          code: "DRX_INVALID_STATE",
          message: "Invalid state. Expected: st name = initialValue.",
          file,
          line: line.no,
        });
      usesState = true;
      body.push({
        type: "statement",
        code: `const [${match[1]}, ${setterName(match[1])}] = useState(${replaceAw(match[2])})`,
        line: line.no,
      });
      index++;
      continue;
    }
    if (line.text.startsWith("ef ")) {
      const match = line.text.match(/^ef\s+(\[.*\])$/);
      if (!match)
        throw new DrxError({
          code: "DRX_INVALID_EFFECT",
          message: "Invalid effect. Expected: ef [deps].",
          file,
          line: line.no,
        });
      const block = collectBlock(lines, index, 2);
      usesEffect = true;
      body.push({
        type: "effect",
        deps: match[1],
        code: block.text,
        line: line.no,
      });
      index = block.next;
      continue;
    }
    body.push({
      type: "statement",
      code: transformStatement(line.text),
      line: line.no,
    });
    index++;
  }

  return { body, next: index, usesState, usesEffect };
}

function transformStatement(text: string) {
  if (text.startsWith("c "))
    return text.replace(
      /^c\s+(.+?)\s*=\s*(.+)$/,
      (_, left, value) => `const ${left} = ${replaceAw(value)}`,
    );
  if (text.startsWith("l "))
    return text.replace(
      /^l\s+(.+?)\s*=\s*(.+)$/,
      (_, left, value) => `let ${left} = ${replaceAw(value)}`,
    );
  if (text.startsWith("r ")) return `return ${replaceAw(text.slice(2).trim())}`;

  return replaceAw(text);
}

function collectBlock(lines: Line[], start: number, childIndent: number) {
  const body = [];

  const numberedLines = [];

  let index = start + 1;

  while (index < lines.length && lines[index].indent >= childIndent) {
    const line = lines[index];
    const trimLevels = Math.min(line.indent, childIndent);
    const prefix = "  ".repeat(line.indent - trimLevels);
    body.push(`${prefix}${line.text}`);
    numberedLines.push(`${line.no}:${prefix}${line.text}`);
    index++;
  }

  return { text: body.join("\n"), numberedLines, next: index };
}
